// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDT6OTWWDQj56FBrLWDeg0WZX24Y67J-8',
    appId: '1:89824530751:android:bdbe1f8c3cd355546dc38a',
    messagingSenderId: '89824530751',
    projectId: 'misiontic-4b',
    databaseURL: 'https://misiontic-4b-default-rtdb.firebaseio.com',
    storageBucket: 'misiontic-4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9fDNSb8rY14XaXQxkpTtG96QFnqugRao',
    appId: '1:89824530751:ios:69e637c6399b76d46dc38a',
    messagingSenderId: '89824530751',
    projectId: 'misiontic-4b',
    databaseURL: 'https://misiontic-4b-default-rtdb.firebaseio.com',
    storageBucket: 'misiontic-4b.appspot.com',
    iosClientId: '89824530751-03qgrfkhgh6mtccf23pnqgsfiqp5phqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.fAuthentication',
  );
}
